import type { Metadata } from "next";
import { Rubik } from 'next/font/google';
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import ReduxProvider from "@/components/ReduxPorvider/ReduxProvider";
import logo from "@/../public/assets/imgs/logo..png";

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Specify desired weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />      <meta name="description" content="موقع بوستاتي هو موقع تواصل اجتماعي " />
        <link rel="icon" href={logo.src} />
      </head>
      <body
        className={rubik.className}
      >
        <Toaster position="top-right" />
        {/* Redux provider for all aplication */}
        <ReduxProvider>
          <div className="w-full overflow-hidden">
            {/* Navbar component */}
            <NavBar />
            {/* pages of website */}
            <div className="min-h-screen  bg-back">
              <div className="mt-[140px] sm:mt-[68px]   py-10 flex-grow relative ">

                {children}

              </div>
            </div>
            {/* Footer component */}
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
